CREATE TABLE RESPONSAVEL(
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (ID)
);