CREATE TABLE RESPONSAVEL(
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_EXCLUSAO TIMESTAMP NOT NULL,
    CONSTRAINT PK_RESPONSAVEL PRIMARY KEY (ID)
);