CREATE TABLE CONTA (
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    NOME VARCHAR(100) NOT NULL,
    SALDO NUMBER(20, 2) NOT NULL,
    SALDO_INICIAL NUMBER(20, 2) NOT NULL,
    TIPO_CONTA VARCHAR(100) NOT NULL,
    ID_RESPONSAVEL BIGINT(100) NOT NULL,
    DATA_CRIACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_ATUALIZACAO TIMESTAMP NOT NULL DEFAULT CURRENT_TIMESTAMP,
    DATA_EXCLUSAO TIMESTAMP,
    CONSTRAINT PK_CONTA PRIMARY KEY (ID),
    CONSTRAINT FK_CONTA_RESPONSAVEL FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL(ID)
);