CREATE TABLE TRANSACAO (
    ID BIGINT(100) NOT NULL AUTO_INCREMENT,
    DATA_TRANSACAO TIMESTAMP NOT NULL,
    VALOR NUMBER(20, 2) NOT NULL,
    DESCRICAO VARCHAR(100) NOT NULL,
    ID_RESPONSAVEL BIGINT(100) NOT NULL,
    ID_CONTA BIGINT(100) NOT NULL,
    TIPO_TRANSACAO VARCHAR(100) NOT NULL,
    CATEGORIA_DESPESA VARCHAR(100),
    CATEGORIA_RECEITA VARCHAR(100),
    ID_CONTA_DESTINO BIGINT(100),
    CREATED_AT TIMESTAMP NOT NULL,
    UPDATED_AT TIMESTAMP NOT NULL,
    DELETED_AT TIMESTAMP,
    CONSTRAINT PK_TRANSACAO PRIMARY KEY (ID),
    CONSTRAINT FK_TRANSACAO_RESPONSAVEL FOREIGN KEY (ID_RESPONSAVEL) REFERENCES RESPONSAVEL(ID),
    CONSTRAINT FK_TRANSACAO_CONTA FOREIGN KEY (ID_CONTA) REFERENCES CONTA(ID),
    CONSTRAINT FK_TRANSACAO_CONTA_DESTINO FOREIGN KEY (ID_CONTA_DESTINO) REFERENCES CONTA(ID)
);